[package]
name = "lotide"
version = "0.1.0"
authors = ["Colin Reeder <colin@vpzom.click>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.5"
hyper-tls = "0.4.1"
tokio-postgres = "0.5.3"
tokio = { version = "0.2.18", features = ["macros"] }
activitystreams = "0.6.2"
trout = "0.1.1"
deadpool-postgres = "0.5.5"
serde_json = "1.0.53"
